version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db:/var/lib/postgresql/data  # This will map the 'db' folder to the container's data directory
    ports:
      - "${EXPOSED_POSTGRES_PORT}:5432"  # Expose port using EXPOSED_POSTGRES_PORT
    env_file:
      - .env
